name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: mkdir -p /tmp/nodejs
    - uses: actions/upload-artifact@v3
      with:
          name: my-artifact
          path: /
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: npm run test
    - name: Deploy to ELB
      uses: chriscohoat/deploy-to-elb-action@master
      with:
        script: /tmp
        autoscaling_group_name: ${{ secrets.AUTOSCALING_GROUP_NAME }}
        ssh_key: ${{ secrets.SSH_KEY }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

   
